# Generated by Django 5.2.4 on 2025-07-10 17:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('plan', models.CharField(choices=[('Hobby', 'Hobby'), ('Pro', 'Pro')], default='Hobby', max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='DeployedApp',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apps', to='api.user')),
            ],
        ),
    ]
